### ISSUE TITLE
Implementation of `http_kwargs`

### ISSUE THREAD

**Issue by svilupp** [tylerjthomas9/GoogleGenAI.jl#11]
Thank you for making the changes wrt https://github.com/tylerjthomas9/GoogleGenAI.jl/issues/9.

I wanted to point out two things I noticed:
- I believe there is a bug in implementation for Vector of Dict [here](https://github.com/tylerjthomas9/GoogleGenAI.jl/blob/4291897d8ad1911155ce5e3bb2cbcd8e07e07926/src/GoogleGenAI.jl#L239). The kwargs should have been expanded (`kwargs...`), but they are provided as is -> ie, they do NOT work (confirmed via testing)
- The current implementation is `httpS_kwargs` not `http_kwargs`. It might be less intuitive for people as package is called HTTP and `http_kwargs` is used by OpenAI and PromptingTools.

**Comment by tylerjthomas9** [comment]
Ah, thank you for catching the bug. I have added http_kwargs to the tests, so hopefully this won't happen again. I have also changed the naming of `https_kwargs`->`http_kwargs` to match OpenAI.jl and PromptingTools. 

#12

**Comment by svilupp** [comment]
Would you please register a new version so I can set the compat bound?

**Comment by tylerjthomas9** [comment]
https://github.com/JuliaRegistries/General/pull/103681

Waiting for it to merge. Thank you for your help and contributions to the ecosystem.

**Comment by svilupp** [comment]
Thank you mister! 🙏
