### ISSUE TITLE
[FR] Add support passing kwargs to HTTP.jl

### ISSUE THREAD

**Issue by svilupp** [tylerjthomas9/GoogleGenAI.jl#9]
It would be great if we could enable passing kwargs to HTTP.jl (eg, retry mechanism, connection pool, etc)

Following the example of OpenAI.jl, all it takes is to provide the open kwargs (`http_kwargs...`) in the `_request` function ([link](https://github.com/tylerjthomas9/GoogleGenAI.jl/blob/6a5b5c8f380a8d61d978794b646033c11bf4fdb6/src/GoogleGenAI.jl#L37)) and expose it as a potential kwarg in the upstream functions (eg, `generate_content` etc) and all their methods

**Comment by tylerjthomas9** [comment]
Added with #10. Registering v0.2.0 now. 

To make passing the http and api kwargs cleaner, I also changed the api kwargs to be a named tuple.

**Comment by svilupp** [comment]
What a turnaround! thank you

**Comment by svilupp** [comment]
Hi @tylerjthomas9,

Just to check - I believe you have implemented `httpS_kwargs` not `http_kwargs`.

I'll go with it on my side and re-map it, but I just wanted to flag it for future releases if it wasn't the intent.
